### ISSUE TITLE
testTopClosenessDirected randomly failing

### ISSUE THREAD

**Issue by kolja-esders** [kit-parco/networkit#14] opened 2017-04-11 12:31 UTC
Set random seed or adjust boundaries.

```
[ RUN      ] CentralityGTest.testTopClosenessDirected
networkit/cpp/centrality/test/CentralityGTest.cpp:871: Failure
The difference between cc.ranking()[i].second and topcc.topkScoresList()[i] is 0.014224715958173262, which exceeds tol, where
cc.ranking()[i].second evaluates to 0.3233387358184765,
topcc.topkScoresList()[i] evaluates to 0.33756345177664976, and
tol evaluates to 9.9999999999999995e-08.
networkit/cpp/centrality/test/CentralityGTest.cpp:871: Failure
The difference between cc.ranking()[i].second and topcc.topkScoresList()[i] is 0.0031140167173528965, which exceeds tol, where
cc.ranking()[i].second evaluates to 0.3202247191011236,
topcc.topkScoresList()[i] evaluates to 0.3233387358184765, and
tol evaluates to 9.9999999999999995e-08.
networkit/cpp/centrality/test/CentralityGTest.cpp:871: Failure
The difference between cc.ranking()[i].second and topcc.topkScoresList()[i] is 0.016802665869184441, which exceeds tol, where
cc.ranking()[i].second evaluates to 0.30342205323193916,
topcc.topkScoresList()[i] evaluates to 0.3202247191011236, and
tol evaluates to 9.9999999999999995e-08.
[  FAILED  ] CentralityGTest.testTopClosenessDirected (20 ms)
```

**Comment by michitux** [comment] 2017-04-11 15:37
This is a duplicate of #6 where I also noted that using seeds does not help.

**Comment by ebergamini** [comment] 2017-06-07 08:54
Fixed bug in TopCloseness code.

**Closed by ebergamini** 2017-06-07 08:54 UTC
