### ISSUE TITLE
Execution time discrepancy ApproximateBetweenness

### ISSUE THREAD

**Issue by sunilkmaurya** [kit-parco/networkit#299] opened 2019-03-08 15:58 UTC
I have installed Networkit using pip. I am calculating approximate betweenness centrality
using ApproxBetweenness() function.
Graph under consideration is p2p-Gnutella31(directed) downloaded from SNAP network dataset
(https://snap.stanford.edu/data/p2p-Gnutella31.html)

When I am using the function without providing any parameters and only graph as input

`approx_bet = centrality.ApproxBetweenness(graph).run().ranking()`
Time taken: 0.963 sec

But if I actually provide epsilon parameter same as default parameter(0.01), it takes longer
duration of time to complete execution.

`approx_bet = centrality.ApproxBetweenness(graph,epsilon=0.01).run().ranking()`
Time taken: 58.805 sec

So for supposedly same epsilon parameter, it is taking different time for execution. Is there something I
am doing wrong? 

Time taken for some other epsilon values:
epsilon = 0.05 , Time taken: 2.645 sec
epsilon = 0.005, Time taken: 236.132 sec

Also, I used Betweenness() function to calculate exact betweenness values and measured the time taken.

`exact_bet = centrality.Betweenness(graph).run().ranking()`
Time taken: 96.718 sec

Why the time taken for epsilon = 0.005 is higher than calculation of exact betweenness centrality
calculation?

I have observed similar trends with some other graphs too. Can anyone please explain the reason behind
it.

**Comment by avdgrinten** [comment] 2019-03-08 17:27
The time taken for very small epsilon might indeed be greater than the time required for an exact computation; this is not a bug but a property of the algorithm. If you want very accurate values, just use the exact algorithm instead.

The issue with the default value is indeed strange - that's something we should investigate.

**Comment by angriman** [comment] 2019-03-13 08:59
There is indeed a discrepancy between default value of `epsilon` used in the Python documentation:
https://github.com/kit-parco/networkit/blob/c33903ee2791ed0db52eb9f0fbdb8b2528044d29/networkit/_NetworKit.pyx#L7270
and the actual one:
https://github.com/kit-parco/networkit/blob/c33903ee2791ed0db52eb9f0fbdb8b2528044d29/networkit/_NetworKit.pyx#L7293
We will keep `epsilon=0.01` as default value to keep in line with the `ApproxBetweenness.hpp` file:
https://github.com/kit-parco/networkit/blob/c33903ee2791ed0db52eb9f0fbdb8b2528044d29/include/networkit/centrality/ApproxBetweenness.hpp#L40

This issue is addressed in #300

**Comment by angriman** [comment] 2019-03-13 09:05
@sunilkmaurya you may also be interested in the new algorithm `KadabraBetweenness` that was introduced in the last NetworKit release and was presented in [this paper](https://arxiv.org/abs/1604.08553). As `ApproxBetweenness` it computes an `epsilon`-approximation of betweenness but should be faster.

**Closed** 2019-03-13 09:06 UTC

**Comment by sunilkmaurya** [comment] 2019-03-13 10:04
Thank you @avdgrinten and @angriman for the information. I really appreciate it. I am actually comparing different betweenness approximation algorithms, so I also looked into `KadbraBetweenness`. It is indeed quite fast. Unfortunately in Networkit, it only supports undirected graphs and I am working with directed graphs too. So for now I am using the code here [https://github.com/natema/kadabra](https://github.com/natema/kadabra).
